### ISSUE TITLE
Mark transition to LetsTrace repo

### ISSUE THREAD

**Issue by Falco20019** [Chatham/LetsTrace.Jaeger#4]
Maybe we should archive this repo or at least at a notification in the `README` that this repo is no longer maintained and was integrated into `LetsTrace`. `LetsTrace` will be moved to Jaeger Org, but GitHub should be able to keep the link working. Or we make the Notification after the move.

**Comment by grounded042** [comment]
I was figuring since this wouldn't be moved to Jaeger org since it's been integrated into LetsTrace. I'll push up some README info and the archive it.
